DELETE FROM nfl_teams;
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Arizona_Cardinals", "Arizona Cardinals", "https://50-best.com/images/nfl_team_wallpapers/arizona_cardinals_wallpaper.jpg", "de760528-1dc0-416a-a978-b510d20692ff", "AZCardinals", "Sam Bradford has now joined his 4th NFL team since being drafted first overall by the Rams only 8 years ago. His arm strength is below average, but his football IQ/ completion percentage is high enough where he is just good enough to start on an NFL team. Who knows how David Johnson is going to play this year? Their offensive line is bad, but he'll surely catch a ton of passes from Bradford, the king of the checkdown. Even with arguably the best defensive player in the league, Tyronn Mathieu, they are still a C minus defense. Maybe the new defensive minded head coach, Steve Wilks, can flip the script, but with their current personnel they sit at number 23.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Atlanta_Falcons", "Atlanta Falcons", "https://50-best.com/images/nfl_team_wallpapers/atlanta_falcons_wallpaper.jpg", "e6aa13a4-0055-48a9-bc41-be28dc106929", "AtlantaFalcons", "Tremendous fire power on the offensive side of the ball. Matt Ryan, the 2017 MVP, is still only 33 years old. Jutro Jones is still elite, having notched 1400 yards on what was considered an ‘off year’ in 2018. They have many other wide receivers who are just freakin’ fast. Their backfield is probably the best in the league, maybe second to the Saints. Devonta Freeman and Tevin Coleman are a disgusting 1-2 combo... or should I say 1-1. The Falcons have had a good offense since the Mike Vick days. But this Falcons team also has a stout defense, led by Deion Jones and Keanu Neal.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Baltimore_Ravens", "Baltimore Ravens", "https://50-best.com/images/nfl_team_wallpapers/baltimore_ravens_wallpaper.jpg", "ebd87119-b331-4469-9ea6-d51fe3ce2f1c", "Ravens", "Maybe losing his job to Lamar Jackson will be the motivation Joe Flacco needs to finally perform even close to the enormous contract extension he signed in 2016. Ravens fans will probably want to see Lamar start, but Flacco is still a Super Bowl MVP and so they are still above average at the most important position with Flacco. If they can squeak into the playoffs I believe they will contend but I doubt that they will with this weak offense. On the flip side, their defense is very good, so you never know.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Buffalo_Bills", "Buffalo Bills", "https://50-best.com/images/nfl_team_wallpapers/buffalo_bills_wallpaper.jpg", "768c92aa-75ff-4a43-bcc0-f2798c2e1724", "buffalobills", "After losing Tyrod Taylor in free agency, the Bills are clearly entering rebuild mode. With a below average defense and a big question mark at the QB spot, the Bills are nothing short of irrelevant.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Carolina_Panthers", "Carolina Panthers", "https://50-best.com/images/nfl_team_wallpapers/carolina_panthers_wallpaper.jpg", "f14bf5cc-9a82-4a38-bc15-d39f75ed5314", "Panthers", "Is Cam the quarterback the we all thought he was after his MVP season? It seemed like he wasn’t after 2016, but he definitely bounced back last year. Cam is immensely talented but supposedly ‘uncoachable’. Nonetheless, they still have a stout defense led by Luke Kuechly and a dynamic pass-catching running back in Christian McCaffrey.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Chicago_Bears", "Chicago Bears", "https://50-best.com/images/nfl_team_wallpapers/chicago_bears_wallpaper.jpg", "7b112545-38e6-483c-a55c-96cf6ee49cb8", "ChicagoBears", "Daa Bears. Is Mitchell Trubisky even decent? He is an enormous question mark that they foolishly sold the farm for. He did show potential last year, with his miniscule work load (27 attempts per game). He also showed skill outside of the pocket, running for 240 yards and 2 touchdowns in 12 games last year. and they just stole Roquan Smith in the draft, who is supposed to be a beast this year. He'll join Danny Trevathan to make up a scary linebacker core. At the running back position they are well above average; with power house Jordan Howard and little quickster Tarik Cohen.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Cincinnati_Bengals", "Cincinnati Bengals", "https://50-best.com/images/nfl_team_wallpapers/cincinati_bengals_wallpaper.jpg", "ad4ae08f-d808-42d5-a1e6-e9bc4e34d123", "Bengals", "A.J. Green is still a top 5 wide receiver, but someone needs to tell the Bengals front office to finally move on from Andy Dalton. He has a very talented supporting cast in A.J. Green, Joe Mixon, and Tyler Eifert, but he has been a starter since 2011 and has 0 playoff wins. Yeah there were some good statistical years, but its about winning, which Dalton fails to do when it really matters. Their defense is average, led by Vontaze Burfict and Geno Atkins, two veteran defensive linemen. Still, they are the third best team in the AFC north.  ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Cleveland_Browns", "Cleveland Browns", "https://50-best.com/images/nfl_team_wallpapers/cleveland_browns_wallpaper.jpg", "d5a2eb42-8065-4174-ab79-0a6fa820e35e", "Browns", "Last and least, the Browns. They are arguably the most interesting team in the league; having signed Tyrod Taylor, Baker Mayfield, Jarvis Landry, and Carlos Hyde. They still have Josh Gordon, and Myles Garret is a beast, but their other 2017 first rounder, Jabrill Peppers, seems to be a huge bust thus far. With the 31st defense in points allowed last year, the Browns have to do more than just sign players before they can ascend from last place, they need to actually win some games.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Dallas_Cowboys", "Dallas Cowboys", "https://50-best.com/images/nfl_team_wallpapers/dallas_cowboys_wallpaper.jpg", "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060", "dallascowboys", "I know, I know. The Cowboys are this low!? Well, Dak Prescott kind of wet the bed last year, even though I still think he is talented. Zeke is still Zeke. The O line lost Ron Leary, but they will still be but overrated target in Dez Bryant, and the defense is mediocre. The Cowboys have the personnel to sky rocket up these rankings, but from what we saw during Zeke's suspension last year, they sit at 20.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Denver_Broncos", "Denver Broncos", "https://50-best.com/images/nfl_team_wallpapers/denver_broncos_wallpaper.jpg", "ce92bd47-93d5-4fe9-ada4-0fc681e6caa0", "Broncos", "In 2015, the Broncos defense was legendary. They carried a shadow of Peyton Manning to a Super Bowl ring. It was known, even then, that the Broncos offense was bad, but they were still the best team in the league because their defense was a pro bowl team. Now, they do not have Danny Trevathan or Aqib Talib. Chris Harris Jr. and Von Miller are still dominant, but as a unit, they’re just slightly above average defensively. They signed Case Keenum, the definition of an interim quarterback, and Demaryius Thomas is still a top 15 receiver. There is nothing exciting about the Broncos besides the two aforementioned studs.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Detroit_Lions", "Detroit Lions", "https://50-best.com/images/nfl_team_wallpapers/detroit_lions_wallpaper.jpg", "c5a59daa-53a7-4de0-851f-fb12be893e9e", "Lions", "Now, we get to the bottom half of the league. Starting with the best below average team in the league: The Lions. Let's start with Matthew Stafford, who is getting paid big bucks. His talent is unquestioned, but the guy can't seem to win enough games. Since 2012, with Stafford, the Lions are flat out average. This year, Stafford has a lot of talent around him. Running back Legarrete Blount, a proven veteran, is in the backfield. Fantasy Football darkhorse Marvin Jones, still in his prime, is coming off an 1100 yard season number 2. However, their defense is really bad.  ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Green_Bay_Packers", "Green Bay Packers", "https://50-best.com/images/nfl_team_wallpapers/green_bay_packers_wallpaper.jpg", "a20471b4-a8d9-40c7-95ad-90cc30e46932", "packers", "Aaron Rodgers is ranked 10. Oops, I mean the Green Bay Packers are ranked 10. I say that because without that man, they are irrelevant. But he is the most talented quarterback in NFL history and so by himself he carries them to the number 9 spot. He is not alone, wide receiver Devante Adams has proven to be a sufficient target for the best QB in the league. Quarterback is the most important position in football, so I’ll keep them here; however, if Aaron Rodgers gets injured again expect them to fall to around 25.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Houston_Texans", "Houston Texans", "https://50-best.com/images/nfl_team_wallpapers/houston_texans_wallpaper.jpg", "82d2d380-3834-4938-835f-aec541e5ece7", "HoustonTexans", "Their defensive line makes most quarterbacks shiver in fear. J.J. Watt and Jadeveon Clowney are a beastly duo, the likes of which this league has never seen before. J.J. Watt is arguably the best defensive player ever and Jadeveon Clowney is looking like he can fill Watt's shoes. And offensively, they get Deshaun Watson back who proved he can absolutely ball out on the NFL level. It doesn’t hurt that he gets to pass to the second best receiver in the league, Deandre Hopkins.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Indianapolis_Colts", "Indianapolis Colts", "https://50-best.com/images/nfl_team_wallpapers/indianapolis_colts_wallpaper.jpg", "82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9", "Colts", "Andrew Luck might be the next Peyton Manning, but his injury might’ve been career threatening. Time will tell. T.Y. Hilton proved last year that he doesn’t need a good quarterback to ball out. They signed a new target for luck: Eric Ebron who hasn’t been able to maintain health, their defense is atrocious, and their kicker is a grandpa.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Jacksonville_Jaguars", "Jacksonville Jaguars", "https://50-best.com/images/nfl_team_wallpapers/jacksonville_jaguars_wallpaper.jpg", "f7ddd7fa-0bae-4f90-bc8e-669e4d6cf2de", "Jaguars", "The Jaguars are a legitimate quarterback away from being Superbowl contenders. Currently, they are on the brink, having Blake Bortles, who to his credit actually played very well last postseason. Nonetheless, he is still Blake Bortles. Their defense is scary good. They have more pro-bowlers on defense than any team in the league. Jalen Ramsey, Calais Campbell, Malik Jackson, Yannick Ngakoue, Telvin Smith, and A.J. Bouye. That is more than HALF of their defense. If you are a defender on the Jaguars, being in the pro bowl doesn’t even mean that you are an above average defender on your squad. Think about that. And oh yeah they have a blue chip young running back in Leanord Fournette who played like a BEAST last year.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Kansas_City_Chiefs", "Kansas City Chiefs", "https://50-best.com/images/nfl_team_wallpapers/kansas_city_chiefs_wallpaper.jpg", "6680d28d-d4d2-49f6-aace-5292d3ec02c2", "Chiefs", "The Chiefs were considered the best team in the league at one point last season. Kareem Hunt had an unreal rookie campaign and in most seasons, would have one the offensive rookie of the year. Unfortunately, he didn't because Alvin Kamara put on a clinic. Their defense is mediocre at best, but their offense has immense potential. I say <i>potential</i> and not <i>talent</i> because no one has seen their quarterback Patrick Mahomes play in an NFL game yet. But the young qb has an elite group of pass-catchers in Tyreke Hill and Travis Kelce.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Los_Angeles_Chargers", "Los Angeles Chargers", "https://50-best.com/images/nfl_team_wallpapers/san_diego_chargers_wallpaper.jpg", "2eff2a03-54d4-46ba-890e-2bc3925548f3", "Chargers", "Phil Rivers, Melvin Gordon, and Keenan Allen are a scary offensive trio. Defensive rookie of the year, Joey Bosa and Melvin Ingram are a scary pass-rushing duo. Their offensive roster is elite, and they could put pressure on the quarterback as good as any team. Although the last 4 years have been ugly for this team, they have a stacked deck and so they deserve the number 12 spot.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Los_Angeles_Rams", "Los Angeles Rams", "https://50-best.com/images/nfl_team_wallpapers/st_louis_rams_wallpapers.jpg", "1f6dcffb-9823-43cd-9ff4-e7a8466749b5", "Rams", "It seems like a dynasty is emerging in Los Angeles. Sean McVey has proven to be an offensive genius. Jared Goff, their first overall pick, showed tremendous promise last season. Todd Gurley is, dare I say, the next Adrian Peterson? Maybe I'm getting ahead of myself with that statement, but he's undoubtably an elite NFL running back. And we can't forget about DT Aaron Donald who held out all of last offseason and came back to win the Defensive Player of the Year Award, talk about raw talent, this guy doesn’t even need to practice. Young and talented are the two words that best describe this franchise. But wait, a young and explosive team also had the best offseason in the NFL? Yup. Enormous credit to the Rams GM for signing Brandin Cooks, Marcus Peters, Aqib Talib, and Ndamukong Suh. Jeez, they signed more studs then most teams have on their whole roster.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Miami_Dolphins", "Miami Dolphins", "https://50-best.com/images/nfl_team_wallpapers/miami_dolphins_wallpaper.jpg", "4809ecb0-abd3-451d-9c4a-92a90b83ca06", "MiamiDolphins", "The Dolphins need to sign players on the defensive side of the ball. They signed target for Ryan Tannehill who played decently well last year, and Devante Parker seems to have some potential. Kenyan Drake shows promise, and we've seen time and time again those Dolphins running backs just explode. The problem: they were 29th in the league last year in points allowed. Yikes.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Minnesota_Vikings", "Minnesota Vikings", "https://50-best.com/images/nfl_team_wallpapers/minnesota_vikings_wallpaper.jpg", "33405046-04ee-4058-a950-d606f8c30852", "Vikings", "There's no other way to put it, the Vikings have a STACKED roster. Offensively? Stacked. Adam Thielen, Stefon Diggs, Kyle Rudolph, and now... Kirk Cousins (signed in free agency) and Dalvin Cook (back from injury). Their defense is number 1 in the NFL with five players having qualified for the 2018 Pro Bowl. Last year, it looked like Case Keenum could take them to the promised land, but then Case Keenum turned into ...well, Case Keenum. They were a franchise quarterback away from having an all-time roster and what did they do? They added one. This could be the Vikings year.  ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("New_England_Patriots", "New England Patriots", "https://50-best.com/images/nfl_team_wallpapers/original_patriots_logo.jpg", "97354895-8c77-4fd4-a860-32e62ea7382a", "Patriots", "This one is no surprise. The Superbowl runner ups are returning this year stronger than last year. With Gronkowski ready to play again, the GOAT Tom Brady gets his favorite target back. They brought in two new defensive assets: young stud Danny Shelton and veteran cornerback Jason McCourty; and you just know HC Bill Belichik will make the most out of them.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("New_Orleans_Saints", "New Orleans Saints", "https://50-best.com/images/nfl_team_wallpapers/new_orlanes_saints_wallpaper.jpg", "0d855753-ea21-4953-89f9-0e20aff9eb73", "Saints", "This team is dangerously similar to their division rivals, that team right ahead of them, the Atlanta Falcons. Both teams have elite veteran quarterbacks. Both teams have elite backfields, the Saints with Mark Ingram and Alvin Kamara who really put on a show last year. Michael Thomas didn't exactly meet his expectations last year, number one. And like the Falcons, they have a great defense led by 2 stars: Cameron Jordan and Marshon Lattimore.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("New_York_Giants", "New York Giants", "https://50-best.com/images/nfl_team_wallpapers/new_york_giants_wallpaper.jpg", "04aa1c9d-66da-489d-b16a-1dee3f2eec4d", "Giants", "Two years ago, they were elite. Then last year, their receivers got injured and so Etr had nobody to pass to and nobody to protect him (their offensive line was abysmal). Now their injured receivers are back and they are an elite group. OBJ and Sterling Sheppard are a top 3 duo in the league. Throw in first rounder, Evan Engram who proved to be legit last year. They signed Nate Solder and drafted a left guard to protect Saquon Barkley, who has the most raw talent coming into the league in NFL history. The guy is just a freak of nature. Their defense is still the same as the 2016-2017 Giants defense that turned so many heads, led by saftey Landon Collins. Let's see what the 2x Super Bowl MVP can make of this squad.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("New_York_Jets", "New York Jets", "https://50-best.com/images/nfl_team_wallpapers/new_york_jets_wallpaper.jpg", "5fee86ae-74ab-4bdd-8416-42a9dd9964f3", "nyjets", "The Jets are definitely interesting this year. But their players need to prove themselves before they can be any higher than 24. It is still not clear who they are going to start at quarterback, but there are rumors that they are going to trade Bridgewater, which would likely lead to McCown starting. McCown will have competition to motivate him with Sam Darnold on the roster. They signed Terrelle Pryor, and Quincy Enunwa is coming back. Robbie Anderson number 1 receiver last year, but his off the field problems are keeping him from playing. Their defense is promising with rising stars Jamal Adams and Leonard Williams. This is an unproven team with a lot of potential.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Oakland_Raiders", "Oakland Raiders", "https://50-best.com/images/nfl_team_wallpapers/oakland_raiders_wallpaper.jpg", "1c1cec48-6352-4556-b789-35304c1a6ae1", "Raiders", "The Oakland Raiders might actually be a top 10 team this year, but they also might implode, and be the next Cleveland Browns. Although their new head coach John Gruden has a Super Bowl ring, he hasn't coached in a decade. They are leaving their loyal fan base in Oakland to go play in Vegas, which might not bode well for them; time will tell. Der quarterback, but he gets little help from the Raiders' bad defense and a running back who is really old.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Philadelphia_Eagles", "Philadelphia Eagles", "https://50-best.com/images/nfl_team_wallpapers/philadelphia_eagles_wallpaper.jpg", "386bdbf9-9eea-4869-bb9a-274b0bc66e80", "Eagles", "They are the Super Bowl champions and have a blossoming, once-in-a-generation quarterback in Carson Wentz. Their offensive line is elite, led by Lane Johnson and Brandon Brooks. Their tight end is elite in Zach Ertz. They have many weapons at receiver that Doug Peterson has proven to utilize efficiently. And oh, they have an elite defense led by Fletcher Cox and Malcolm Jenkins. It would be blasphemous to put them anywhere lower than number one.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Pittsburgh_Steelers", "Pittsburgh Steelers", "https://50-best.com/images/nfl_team_wallpapers/pittsburgh_steelers_wallpaper.jpg", "cb2f9f1f-ac67-424e-9e72-1475cb0ed398", "steelers", "This is a team that seems to be glued to a ranking between 3 and 6. They have arguably the most loaded offense in NFL history. Antonio Brown, top 5 receiver of all time, paired with JuJu Smith-Schuster, a number 2 receiver who would be the number 1 receiver on 60% of teams. They also have Leveon Bell, who is widely considered the best running back in the NFL and an all-time great. And the nucleus of this high-powered offense, Ben Roethlisberger, a 2x Super Bowl Champion still has a good 3-4 years left. If they didn't choke in the playoffs every year they could be number 1.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("San_Francisco_49ers", "San Francisco 49ers", "https://50-best.com/images/nfl_team_wallpapers/san_francisco_49ers_wallpaper.jpg", "f0e724b0-4cbf-495a-be47-013907608da9", "49ers", "Jimmy Garrappolo. The 49ers seemed not only bad, but uninteresting until this guy came out of nowhere. Now, this is a team with a lot of promise, but did they grossly overpay Jimmy G? It's debatable. Head coach Kyle Shanahan is one of the best offensive minds in the game. They have the best fullback in the league, paired with a newly acquired running back in Jerrock McKinnon. And oh yeah, remember that guy Richard Sherman? They signed him too and he seems to be poised for another great year.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Seattle_Seahawks", "Seattle Seahawks", "https://50-best.com/images/nfl_team_wallpapers/seattle_seahawks_wallpaper.jpg", "3d08af9e-c767-4f88-a7dc-b920c6d2b4a8", "Seahawks", "How long has it been since Seattle entered the season ranked this low? The only thing that the Seahawks have to be excited about is their ol' reliable: Russel Wilson. Wilson is a bonified MVP candidate who can cancel out all of the noise and ball out every year. They lost Richard Sherman, who joined their division rivals, Kam Chancellor retired, Bobby Wagner is holding out, and Cliff Avril is coming off of a career-threatening neck injury. It looks like rebuilding time in Seattle, starting with rookie running back Sonny Mitchell.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Tampa_Bay_Buccaneers", "Tampa Bay Buccaneers", "https://pre00.deviantart.net/0794/th/pre/f/2014/173/2/1/tampa_bay_buccaneers_by_beaware8-d7nhi97.jpg", "4254d319-1bc7-4f81-b4ab-b5e6f3402b69", "Buccaneers", "The Buccaneers are definitely the most interesting team in the bottom 10. I still believe Jameis Winston can emerge into an elite player. Yeah, I said it, ELITE. When that man is on his game, he is virtually unstoppable. He completed 64 percent of his passes last year and gets to throw to a top 5 receiver in Mike Evans and a veteran speedster in Deshaun Jackson. We'll see how rookie Ronald Jones II turns out this year, but with the 24th ranked defense and a suspended quarterback, the Bucks are not scaring anyone.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Tennessee_Titans", "Tennessee Titans", "https://50-best.com/images/nfl_team_wallpapers/tennessee_titans_wallpaper.jpg", "d26a1ca5-722d-4274-8f97-c92e49c96315", "Titans", "Derrick Henry and Marcus Mariota are an exceptional young core for Tennessee’s front office to build around. Their defense is elite, led by Pro Bowler Jurrell Casey. And let's not forget that they made a nice run in the playoffs last year where Mariota threw a pass to himself to beat the Chiefs.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("Washington_Redskins", "Washington Redskins", "https://50-best.com/images/nfl_team_wallpapers/washington_redskins_wallpaper.jpg", "22052ff7-c065-42ee-bc8f-c4691c50e624", "Redskins", "Their offense will be interesting going into this year. With a proven veteran at quarterback, the Redskins will likely be running with a three-man backfield this year in Derrius Guice, Chris Thompson, and Robert Kelley. Remember those last 2 had ridiculous fantasy weeks last year? Maybe the Redskins can replicate that effort and form a formidable offense. The problem is they have a brutal defense, who were tied for 27th in the league in points allowed last year. Another problem is: who is Alex Smith going to pass to this year? We know he likes throwing to tight ends but the guy has only one decent target in Jordan Reed.", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO nfl_teams (team_long_id, team_name, display_url, api_team_access_id, twitter_handle, projection, createdAt, updatedAt)
VALUES ("NFL", "NFL", "https://50-best.com/images/nfl_team_wallpapers/nfl_on_black_wallpaper.jpg", "x", "NFL", "x", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
